export const GET_PATIENT = "GET_PATIENT";
export const LOAD_PATIENT = "LOAD_PATIENT";
export const FAIL_PATIENT = "FAIL_PATIENT";
export const GETONE_PATIENT = "GETONE_PATIENT";
export const CURRENT_PATIENT = "CURRENT_PATIENT";
export const LOGIN_PATIENT = "LOGIN_PATIENT";
export const REGISTER_PATIENT = "REGISTER_PATIENT";
export const LOGOUT_PATIENT = "LOGOUT_PATIENT<";

