export const GET_RENDEZVOUS = "GET_RENDEZVOUS";
export const LOAD_RENDEZVOUS = "LOAD_RENDEZVOUS";
export const FAIL_RENDEZVOUS = "FAIL_RENDEZVOUS";
export const GETONE_RENDEZVOUS = "GETONE_RENDEZVOUS";
